live_config_reload = true

# Windows only
# [shell]
# program = "C:\\Windows\\System32\\wsl.exe ~"
# args = ["-d Ubuntu-24.04"]

[window]
opacity = 0.8
padding.x = 16
padding.y = 16
decorations = "buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 14.0

[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"
